src/app/header/header/header.component.html, src/app/home/home/home.component.scss, src/app/services/auth.service.ts
=> feat(header): ログアウト機能追加 fix #3

.prettierrc, package-lock.json, package.json
コミット時にprettierで自動整形するようにしました。
ご確認よろしくお願いします。
- add prettierrc
=> prettierで自動整形

src/app/event/event-form/event-form.component.ts, src/app/services/event.service.ts
イベント編集と削除機能を追加しました。
編集の際のeventIdはparamsから取っているので、編集ボタンクリック時のルーティングで設定しましょう。
削除は機能のみ追加しています。
- add updateEvent
- add DeleteEvent
=> イベント編集機能追加 Feature/5

src/app/home/event-card/event-card.component.html, src/app/home/event-card/event-card.component.scss, src/app/home/event-card/event-card.component.ts, src/app/home/home/home.component.html, src/app/home/home/home.component.ts
イベント一覧に実データの表示繋ぎ込みしました。
イベント詳細表示と遷移はダイアログとし、次issueで対応します。
=> イベント一覧表示 Feature/23

functions/src/index.ts, functions/src/reserve.event.function.ts, functions/src/utils/firebase.util.ts, src/app/home/event-card/event-card.component.scss, src/app/home/event-card/event-card.component.ts, src/app/home/event-detail-dialog/event-detail-dialog.component.html, src/app/home/event-detail-dialog/event-detail-dialog.component.scss, src/app/home/event-detail-dialog/event-detail-dialog.component.spec.ts, src/app/home/event-detail-dialog/event-detail-dialog.component.ts, src/app/home/home.module.ts, src/app/home/home/home.component.html, src/app/interfaces/event.ts, src/app/interfaces/reserve-uid.ts, src/app/services/event.service.ts
イベント詳細ダイアログを追加しました。
追加で、イベント予約機能を追加し、現在●人参加予定のUIを作成しました。
- add reserveEvent
- add event-detail-dialog
- add countUpReserveUser function
=> イベント詳細表示　Feature/24

src/app/event/chat/chat.component.html, src/app/event/chat/chat.component.scss, src/app/event/event-room/event-room.component.html, src/app/event/event-room/event-room.component.scss, src/app/event/event-room/event-room.component.ts, src/app/event/stream/stream.component.scss, src/app/header/header/header.component.scss, src/app/home/event-card/event-card.component.scss, src/app/home/home/home.component.scss, src/app/interfaces/event.ts, src/app/services/event.service.ts
=> feat(room): UI調整 fix #34

src/app/event/stream/stream.component.ts, src/app/home/event-calendar/event-calendar.component.html, src/app/home/event-calendar/event-calendar.component.scss, src/app/home/event-calendar/event-calendar.component.ts, src/app/home/event-card/event-card.component.html, src/app/home/event-card/event-card.component.scss, src/app/home/event-detail-dialog/event-detail-dialog.component.html, src/app/home/event-detail-dialog/event-detail-dialog.component.scss, src/app/home/event-detail-dialog/event-detail-dialog.component.ts, src/app/home/home.module.ts, src/app/home/home/home.component.html, src/app/home/home/home.component.scss, src/app/home/home/home.component.ts, src/app/services/agora.service.ts, src/app/services/event.service.ts, src/assets/images/grid.svg, src/styles.scss
以下の作業を行いました。
ご確認よろしくお願いします。
- イベント詳細ダイアログに予約ユーザーの表示
- イベント詳細ダイアログにオーナーの表示
=> 予約ユーザーリストとオーナーの表示　Feature/49

src/app/event/stream/stream.component.ts, src/app/home/event-calendar/event-calendar.component.html, src/app/home/event-calendar/event-calendar.component.scss, src/app/home/event-calendar/event-calendar.component.ts, src/app/home/event-card/event-card.component.html, src/app/home/event-card/event-card.component.scss, src/app/home/home/home.component.html, src/app/home/home/home.component.scss, src/app/home/home/home.component.ts, src/app/services/agora.service.ts, src/app/services/event.service.ts, src/styles.scss
以下の修正を行いました。
ご確認よろしくお願いします。
- ログイン前ユーザー時の表示修正
- 予約イベントがないユーザーのカレンダー表示
- 退室前にウィンドウ閉じた際のleaveCannel
- 予約人数、参加中人数表示
- homeに表示するイベントは開催中か開催前のもののみに修正
=> ホーム画面の表示修正など Feature/50

src/app/event/stream/stream.component.html, src/app/event/stream/stream.component.ts, src/app/services/agora.service.ts, src/app/settings/settings/settings.component.html, src/app/shared/shared.module.ts
Fixes #58
最初はミュートにしました。ご確認お願いいたします！
=> ルーム入室時はミュートにする

src/app/event/stream/stream.component.ts, src/app/services/agora.service.ts, src/app/shared/share-screen-info-dialog/share-screen-info-dialog.component.html, src/app/shared/share-screen-info-dialog/share-screen-info-dialog.component.spec.ts, src/app/shared/share-screen-info-dialog/share-screen-info-dialog.component.ts, src/app/shared/shared.module.ts
Fixes #82
https://www.loom.com/share/8d5d67ed76c84bc6a27b7bfa62ea13c1
=> Agora: 設定でブラウザに画面共有の許可を出さないとエラーが出るので、ダイアログで案内を表示

src/app/event/stream/stream.component.html, src/app/event/stream/stream.component.scss, src/app/event/stream/stream.component.ts, src/app/services/agora.service.ts
Fixes #61
Fixes #86 
https://www.loom.com/share/58911328924f4268a3432e45eb862e35
=> feat(stream): 画面共有時に自分のスクリーンにも表示

src/app/editor/editor/editor.component.html, src/app/event/event-detail/event-detail.component.html, src/app/event/event-detail/event-detail.component.scss, src/app/event/event-detail/event-detail.component.spec.ts, src/app/event/event-detail/event-detail.component.ts, src/app/event/event-routing.module.ts, src/app/event/event.module.ts, src/app/search-box/search-box.component.html, src/app/search/search-result/search-result.component.html, src/app/search/search-result/search-result.component.scss, src/app/search/search-result/search-result.component.ts, src/app/search/search.module.ts, src/app/shared/event-card/event-card.component.html, src/app/shared/event-card/event-card.component.scss, src/app/shared/event-card/event-card.component.ts, src/app/shared/event-detail-dialog/event-detail-dialog.component.html, src/app/shared/event-detail-dialog/event-detail-dialog.component.ts, src/styles.scss
- イベント作成のバグ修正
- イベント詳細のコンポーネント追加
- 検索結果画面のUI調整
ご確認よろしくお願いします。
=> イベント詳細のコンポーネント追加など Feature/46

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/my-page/my-page/my-page.component.ts, src/app/not-found/not-found.component.html, src/app/not-found/not-found.component.scss, src/app/not-found/not-found.component.spec.ts, src/app/not-found/not-found.component.ts
=> feat(not-found): ４０４画面

src/app/event/event-detail/event-detail.component.html, src/app/event/event-detail/event-detail.component.scss, src/app/footer/footer.component.scss, src/app/header/header/header.component.html, src/app/header/header/header.component.scss, src/app/home/event-calendar/event-calendar.component.ts, src/app/home/home/home.component.scss, src/app/my-page/my-page/my-page.component.html, src/app/my-page/my-page/my-page.component.scss, src/app/search-box/search-box.component.scss, src/app/search/search-result/search-result.component.scss, src/app/search/search-result/search-result.component.ts, src/app/search/search.module.ts, src/app/search/search/search.component.html, src/app/search/search/search.component.scss, src/app/search/search/search.component.ts, src/app/services/event.service.ts, src/app/settings/profile/profile.component.html, src/app/settings/profile/profile.component.scss, src/app/settings/settings/settings.component.html, src/app/settings/settings/settings.component.scss, src/app/shared/event-card/event-card.component.ts, src/app/shared/event-detail-dialog/event-detail-dialog.component.html, src/app/shared/event-detail-dialog/event-detail-dialog.component.scss, src/styles.scss
各コンポーネントのSP対応完了しました。
ご確認よろしくお願いいたします。
=> SP対応　Feature/48

src/app/app.module.ts, src/app/auto-open-login-menu/auto-open-login-menu.component.html, src/app/auto-open-login-menu/auto-open-login-menu.component.scss, src/app/auto-open-login-menu/auto-open-login-menu.component.spec.ts, src/app/auto-open-login-menu/auto-open-login-menu.component.ts, src/app/header/header/header.component.html, src/app/header/header/header.component.scss, src/app/header/header/header.component.ts, src/app/services/auth.service.ts, src/styles.scss
close #107 
- twitter, facebook, github のよるログイン追加
（facebookだけlocalhostでログインするには下記スクショのとおり少し手間がかかる為テストしていません。他はログインチェック済みです。）
ログインUI
https://www.loom.com/share/114d14e8c03d4a6b9c2fb789ea5e88ea
=> SNSログイン機能追加

firestore.rules
=> firestoreルール：テスト環境が昨日までだったのでルールを書き換える

src/app/interfaces/room.ts, src/app/meeting/meeting-room/meeting-room.component.html, src/app/meeting/meeting-room/meeting-room.component.ts, src/app/services/meeting.service.ts, src/app/shared/user-list/user-list.component.ts
Fixes #112
オーナー(招待した人)か否かによって通信開始ボタンは非表示(オーナーには表示されない)、招待された人が通信開始ボタンを押したら通話が始まるように変更。
https://www.loom.com/share/fdfa377b8bd8428f93ff1d1de4212ff6
=> WebRTC: 招待した人と招かれた人で処理を切り替え

src/app/auto-open-login-menu/auto-open-login-menu.component.scss, src/app/footer/footer.component.html, src/app/header/header/header.component.scss, src/app/intl/about/about.component.html, src/app/intl/about/about.component.spec.ts, src/app/intl/about/about.component.ts, src/app/intl/intl-routing.module.ts, src/app/intl/intl.module.ts, src/app/services/auth.service.ts, src/app/settings/account/account.component.html, src/app/settings/account/account.component.ts
=> yuki-kouno/issue123

functions/src/push.messaging.functions.ts, functions/src/user.function.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/interfaces/user.ts, src/app/services/messaging.service.ts, src/app/services/user.service.ts, src/app/settings/notifications/notifications.component.html, src/app/settings/notifications/notifications.component.scss, src/app/settings/notifications/notifications.component.ts, src/app/settings/privacy/privacy.component.scss, src/app/settings/profile/profile.component.html, src/app/settings/profile/profile.component.scss, src/app/settings/profile/profile.component.ts, src/app/shared/shared.module.ts, src/app/shared/user-card/user-card.component.html, src/app/shared/user-card/user-card.component.scss, src/app/shared/user-card/user-card.component.spec.ts, src/app/shared/user-card/user-card.component.ts, src/app/shared/user-list/user-list.component.html, src/app/shared/user-list/user-list.component.scss, src/app/shared/user-list/user-list.component.ts
タイトルの作業を行ないました。
1on1のユーザーリストはタブ的なので、すべて、オンライン、フォローに分けました。
プロフィール編集において、画像だけ変更しても更新できない仕様を修正しました。
=> プッシュ通知のUI作成、user-listのUI作成、プロフィール編集の修正　Feature/108+

functions/src/push.messaging.functions.ts, src/app/app.component.html, src/app/app.component.ts, src/app/editor/editor/editor.component.ts, src/app/my-page/my-page/my-page.component.ts, src/app/services/chat.service.ts, src/app/services/event.service.ts, src/app/services/meeting.service.ts, src/app/services/messaging.service.ts, src/app/services/user-follow.service.ts, src/app/services/user.service.ts, src/app/settings/notifications/notifications.component.html, src/app/settings/notifications/notifications.component.ts, src/app/settings/profile/profile.component.ts, src/app/shared/user-list/user-list.component.ts, src/firebase-messaging-sw.js
- updateUser修正、アバターをstorageにセットするよう変更(base64をそのままfirestoreに入れない)
- 通知設定ボタンの修正
- スマホ時のfirebaseエラー修正
プッシュ通知がらみのログを見たいので、console.log残してますがご了承ください。
=> firebaseのインポートエラー修正など　Feature/118

src/environments/environment.prod.ts, src/firebase-messaging-sw.js
environmentにdatabaseURLが入ってなかったのと、
messagingをサポートしてない時の条件分岐を追加しました。
一旦、これで試してみていいですか。
=> Fix firebase.messaging Feature/118+

firestore.indexes.json, package-lock.json, package.json, src/app/app-routing.module.ts, src/app/home/home-routing.module.ts, src/app/home/home.module.ts, src/app/home/home/home.component.html, src/app/home/home/home.component.scss, src/app/home/home/home.component.ts, src/app/home/special/special.component.html, src/app/home/special/special.component.scss, src/app/home/special/special.component.spec.ts, src/app/home/special/special.component.ts, src/app/interfaces/event.ts, src/app/services/event.service.ts, src/app/shared/event-card/event-card.component.html, src/app/shared/event-card/event-card.component.ts, src/app/shared/user-card/user-card.component.scss, src/app/welcome/welcome-routing.module.ts, src/app/welcome/welcome.module.ts, src/app/welcome/welcome/welcome.component.html, src/app/welcome/welcome/welcome.component.scss, src/app/welcome/welcome/welcome.component.spec.ts, src/app/welcome/welcome/welcome.component.ts, src/styles.scss
- swiper.js追加
- gallery-top, gallery-thumbs追加
- sp対応
- user.cardのbutton表示修正
=> heroにspecialコンポーネント追加 Feature/47

src/app/app.component.html, src/app/search-box/search-box.component.scss, src/app/settings/profile/profile.component.scss
上記タイトルについて、修正しました。
ご確認よろしくお願いします。
- フォアグラウンド時の通知UI修正
- profile設定画面のタブレットUI修正
- タブレット時のsearch-boxUI修正
=> プッシュ通知UI修正、設定画面のタブレットUI修正　Feature/118+++

src/app/event/chat/chat.component.ts, src/app/event/event-room/event-room.component.html, src/app/event/event-room/event-room.component.scss, src/app/event/event-room/event-room.component.ts, src/app/services/log.service.ts, src/app/shared/event-card/event-card.component.ts, src/app/shared/log-card/log-card.component.html, src/app/shared/log-card/log-card.component.scss, src/app/shared/user-list/user-list.component.ts, src/styles.scss
- agora全画面切り替えのボタンと戻すボタン追加
- logsが一人分しか表示されないバグ修正
- イベント参加は開始10分前から入室できるよう変更
=> agora 全画面表示追加 Feature/106

firestore.indexes.json
Fixes #150
- firestore:indexesをfirestore.indexes.jsonに追加
=> Gihthub Actions エラー修正

src/app/my-page/my-page/my-page.component.html, src/app/my-page/my-page/my-page.component.ts, src/app/shared/user-store/user-store.component.html, src/app/shared/user-store/user-store.component.ts, src/app/users/user-card/user-card.component.html, src/app/users/user-card/user-card.component.ts, src/app/users/user-list/user-list.component.html, src/app/users/user-list/user-list.component.ts, src/app/waiting/waiting.module.ts, src/app/waiting/waiting/waiting.component.html, src/app/waiting/waiting/waiting.component.scss, src/app/waiting/waiting/waiting.component.ts
Fixes #167
- my-pageの話しかけるボタン削除
- OneOnOne userCardからチケット購入後入室までの導線追加
=> OneOnOne通話導線修正

.github/workflows/main.yml, firebase.json, functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/src/render.function.ts
=> OGP対応 - ３H

src/app/app.module.ts, src/app/editor/editor.module.ts, src/app/editor/editor/editor.component.html, src/app/editor/editor/editor.component.scss, src/app/editor/editor/editor.component.ts, src/app/event/chat/chat.component.html, src/app/event/chat/chat.component.ts, src/app/home/event-detail/event-detail.component.html, src/app/home/home.module.ts, src/styles.scss
- イベント作成画面のイベント詳細入力フォームをngx-quillに変更
- イベント詳細画面のイベント詳細をquill-viewに変更
- 上記に伴うチャット入力フォーム修正
=> イベント作成画面にQuill追加 Feature/183++

functions/src/stripe/payment-method.function.ts, src/app/editor/editor/editor.component.html, src/app/editor/editor/editor.component.ts, src/app/services/connected-account.service.ts, src/app/settings/profile/profile.component.html, src/app/settings/profile/profile.component.ts, src/app/shared/register-card/register-card.component.html, src/app/shared/register-card/register-card.component.scss, src/app/shared/register-card/register-card.component.ts
closed #187 #188
###作業内容
- loadingUI調整
- クレカ更新バグ修正
=> ui調整 #187 #188

src/app/editor/editor/editor.component.html, src/app/editor/editor/editor.component.ts, src/app/services/event.service.ts, storage.rules
Fixes #192
作成時点ではサムネイル画像を必須入力にして、編集時サムネイル画像が編集されていなかったらアップロード処理が走らないように変更しました。
https://www.loom.com/share/ab0d717c6f7546dbac45489c3999ff77
=> fix(editor): サムネイル画像を添付しないとエラーになるのを修正

src/app/home/event-detail/event-detail.component.html, src/app/home/event-detail/event-detail.component.scss, src/app/shared/event-card/event-card.component.html, src/app/shared/event-card/event-card.component.ts
Fixes #193
###作業内容
- イベントカード遷移先調整
- イベント詳細UI調整
=> イベントカードclick時、詳細画面へ遷移に統一
